### ISSUE TITLE
allowed_origins + whitelist behaviour

### ISSUE THREAD

**Issue by jsalatiel** [mvo5/unattended-upgrades#29]
Hi, whats the correclty expected output from the config below ? 

Unattended-Upgrade::Allowed-Origins {
      `"Ubuntu:xenial-security";`
};
Unattended-Upgrade::Package-Whitelist {
   ` "firefox";`  
};

From what i was expecting, this would allow all  packages from xenial-security be upgraded PLUS firefox from any origin. But it appears to  allow ONLY firefox AND if coming from xenial-security.
Is this the expected behavior ? Can this behavior be customized ?

Thanks !

**Comment by GhostLyrics** [comment]
## how black- and whitelisting works
>Is this the expected behavior ?

Yes.

The way it works is:
- a list of all allowed origins is built
- if no whitelist exists and no blacklist exists => all packages from those origins are upgraded if possible
- if a whitelist exists => only packages on whitelist will be upgraded
- if a blacklist exists => all packages but those on blacklist will be upgraded

What you are currently doing - and that is **a quite dangerous situation** is suppressing security updates aside from Firefox. Please don't do that, you're compromising your system security.

## how to achieve your requested idea

I assume that you want firefox updates that are from another source than *-security.

- You want to list both security and other origin in the `Allowed-Origins`. (I use the more recent `Origins-Pattern` in the example)
- You want the whitelist to be empty.

```
Unattended-Upgrade::Origins-Pattern {
       	"o=${distro_id},a=${distro_codename}-security";
       	"o=${distro_id},a=${distro_codename}-updates";
       	"o=LP-PPA-xorg-edgers,a=${distro_codename}";
};
```

**Comment by jsalatiel** [comment]
Hi  GhostLyrics, thanks for the help.
The only problem i see with the "how to achieve your requested idea" thing is that when i put the "o=${distro_id},a=${distro_codename}-updates";" origin, it will update a lot more packages than just firefox ( or dependencies ).

I used firefox just as one example, the real problem is that i have several servers with just a small internet "quote", and there are a few packages outside the security origin that i have to keep updated to the latest version. So i was trying to find a way to keep updating security, and just a few extra packages from any repository ( and its dependencies of course ) using unnatended-upgrade but i think it cant be done right now. Thank you very much for you help !

**Comment by GhostLyrics** [comment]
@jsalatiel The way to work around your limited bandwidth would be to set up a an APT proxy. You then point all your servers at your proxy and only that one fetches packages (if needed), otherwise you just get your package instantly from the proxy. Speeds up things quite a lot too for upgrades/new installs.

You end up downloading things once instead of once per server. :)

e.g. [apt-cacher ng](https://www.unix-ag.uni-kl.de/~bloch/acng/)

**Comment by jsalatiel** [comment]
@jsalatiel, unfortunately in this case wont be possible. Every server is a standalone server in a very remote location :/
Thanks !

**Comment by GhostLyrics** [comment]
Can you close this issue since it's clearly not a problem of unattended-upgrades?

**Comment by jsalatiel** [comment]
Sure!

**Comment by jsalatiel** [comment]
I think you haven't seen my updated question, so i will just ask again =)
Out of curiosity, is there any security issue that i dont see that would make implement this feature unfeasible?

**Comment by GhostLyrics** [comment]
I don't think that there security considerations here, it's more that you would have to resolve dependencies of whitelisted things (amongst some other changes) which would make this complex. Personally I also find your proposed change confusing (you'd whitelist one package but also implicitly several dependencies).

If you still insist on using unattended-upgrades for this job - where it's not really all that well suited - you can instead set up your own repository with just the packages you want to have auto-updated on those servers and add that to allowed sources. *I wouldn't bother though since manual package update management is quite a lot of work and easy to get wrong.*

**Comment by jsalatiel** [comment]
Hi @GhostLyrics , i was able to achieve my desired goal with a few changes in the unattended-upgrade script. I will let the patch here just in case of someone find this issue and needs it. Thanks!
[patch.txt](https://github.com/mvo5/unattended-upgrades/files/441132/patch.txt)
